name: "Github Release"
on:
  workflow_dispatch:

jobs:
  github-release:
    name: github-release
    runs-on: ubuntu-latest
    steps:
      #Check out
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - run: yarn install

      #Create github releases
      - uses: ./.github/actions/create-release
        with:
          package-path: packages/cli
          repo-token: ${{ secrets.REPO_TOKEN }}

      - uses: ./.github/actions/create-release
        with:
          package-path: packages/common
          repo-token: ${{ secrets.REPO_TOKEN }}

      - uses: ./.github/actions/create-release
        with:
          package-path: packages/common-substrate
          repo-token: ${{ secrets.REPO_TOKEN }}

      - uses: ./.github/actions/create-release
        with:
          package-path: packages/common-terra
          repo-token: ${{ secrets.REPO_TOKEN }}

      - uses: ./.github/actions/create-release
        with:
          package-path: packages/contract-processors
          repo-token: ${{ secrets.REPO_TOKEN }}

      - uses: ./.github/actions/create-release
        with:
          package-path: packages/node
          repo-token: ${{ secrets.REPO_TOKEN }}

      - uses: ./.github/actions/create-release
        with:
          package-path: packages/node-terra
          repo-token: ${{ secrets.REPO_TOKEN }}

      - uses: ./.github/actions/create-release
        with:
          package-path: packages/query
          repo-token: ${{ secrets.REPO_TOKEN }}

      - uses: ./.github/actions/create-release
        with:
          package-path: packages/types
          repo-token: ${{ secrets.REPO_TOKEN }}

      - uses: ./.github/actions/create-release
        with:
          package-path: packages/types-terra
          repo-token: ${{ secrets.REPO_TOKEN }}

      - uses: ./.github/actions/create-release
        with:
          package-path: packages/validator
          repo-token: ${{ secrets.REPO_TOKEN }}
