on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  release:
    if: "!startsWith(github.event.head_commit.message, '[SKIP CI]') && startsWith(github.event.head_commit.message, '[release]') && github.repository == 'subquery/subql'"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      #Identify changes
      - uses: marceloprado/has-changed-path@v1
        id: changed-common
        with:
          paths: packages/common

      - uses: marceloprado/has-changed-path@v1
        id: changed-cli
        with:
          paths: packages/cli

      - uses: marceloprado/has-changed-path@v1
        id: changed-types
        with:
          paths: packages/types

      - uses: marceloprado/has-changed-path@v1
        id: changed-node
        with:
          paths: packages/node

      - uses: marceloprado/has-changed-path@v1
        id: changed-query
        with:
          paths: packages/query

      - uses: marceloprado/has-changed-path@v1
        id: changed-validator
        with:
          paths: packages/validator

      #Create Github Releases
      - run: npm install

      - name: Release Cli
        if: steps.changed-cli.outputs.changed == 'true'
        run: node gh-release-script.js ./packages/cli
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}

      - name: Release Common
        if: steps.changed-common.outputs.changed == 'true'
        run: node gh-release-script.js ./packages/common
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
      
      - name: Release Node
        if: steps.changed-node.outputs.changed == 'true'
        run: node gh-release-script.js ./packages/node
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
      
      - name: Release Query
        if: steps.changed-query.outputs.changed == 'true'
        run: node gh-release-script.js ./packages/query
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
      
      - name: Release Types
        if: steps.changed-cli.outputs.changed == 'true'
        run: node gh-release-script.js ./packages/types
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
      
      - name: Release Validator
        if: steps.changed-validator.outputs.changed == 'true'
        run: node gh-release-script.js ./packages/validator
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
